services:
  cli:
    build: .
    user: "8888"
    working_dir: /workspace
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DOCKER_GID=${DOCKER_GID:-999}
    restart: "no"
    volumes:
      - ${CC_WORKDIR:-${PWD}}:/workspace
      - /var/run/docker.sock:/var/run/docker.sock
      - home:/home/user

volumes:
  home:
